### ISSUE TITLE
Frontend Redesign 

### ISSUE THREAD

**Issue by luisliz** [LibrePhotos/librephotos#126]
So I finally got this great service running and i'm in love. I love good UIs so I started to make a concept to see if you guys would like it. I started to look at the react code and felt like it had a lot of components which most of UI frameworks already do. So, I decided to start it with Vue + Vuetify (It's the one i'm fastest in). If I could get some help with understanding the API i'm willing to revamp it completely as to not put burden on the main developers working on the backend. I hope we can make this better than google photos! 😄 

Some improvements i'm thinking: 
- The almighty Dark mode (done) 
- Highlight for selecting faces for labeling. To not have to click 100 times. 
- More modern data visualization gui. I've used [Charts.js](https://www.chartjs.org/) and it works well.  
- Clicking menu takes you to default instead of having to choose "with timestamp" etc. 
- Sub menus on hover 
- Many faces on label instead of a list for quicker labeling.  
- Some Mobile friendliness 
- Collapse labeled faces 
 
Here is a video: 
https://youtu.be/VZwMPF_J9lU

Here is the code for anyone curious: 
https://github.com/luisliz/librephotos-frontend/tree/vue-refactor

P.S. The importing and completed would disappear accordingly

**Comment by derneuere** [comment]
@luisliz Thanks for the great redesign and the initiative! 👍  I like the new features. I like dark mode too, I like the wall layout instead of rectangles and I like that the search bar fills the whole top bar. I also like that the progress of the scanning is at the side.

I do however would prefer if you could work with the old frontend with react and improved it incrementally instead. The reasoning is that rewrites of complete apps are usually more expensive and lead to regressions. This is something I had to learn myself and [others learned too](https://www.joelonsoftware.com/2000/04/06/things-you-should-never-do-part-i/). Unexpected things I can think of that the API is not documented and the JSON responses are not uniform, which will lead to a lot of headaches. There are probably more unknown Unknowns.

**Comment by luisliz** [comment]
I see what you mean and thinking about it implementing everything from scratch will definitely be a bigger headache which I underestimated at the time of posting.

**Comment by derneuere** [comment]
I added the avatar on the right side :)

**Comment by nagarrido** [comment]
It looks great! Any update on this?

**Comment by derneuere** [comment]
Add new layout for pictures and we now have a centered search bar.

**Comment by derneuere** [comment]
Most of this issue is already implemented or is documented in other issues :)
