### ISSUE TITLE
Issue with downloading the contents of an album...

### ISSUE THREAD

**Issue by miniMUSK** [LibrePhotos/librephotos#1335]
# 🐛 Bug Report

* [X ] 📁 I've Included a ZIP file containing my librephotos `log` files
* [X was instructed by [derneuere] to open bug report from ticket#375 ] ❌ I have looked for similar issues (including closed ones)
* [ ] 🎬 (If applicable) I've provided pictures or links to videos that clearly demonstrate the issue 

## 📝 Description of issue:
Below is my post from Ticket #375
"I am also having issues with downloading pictures. I am trying to download just one album worth of pictures (120 photos) however, when I select the album and select all photos, then download, nothing happens. If i go to the photos tab and select all it does download a ZIP file but the download only takes about 5 seconds and there are only 18 photos in the download when I selected all my photos (over 4k). When I go to my worker log it does not show anything for Download Selected Photos like the picture above from @loulou91, I am very new to LibrePhotos only started using it a couple months ago. I love it but besides making it accessible publicly (not a simple way?), this has been my first obstacle since starting to use it and now I am seeking guidance..."

[ownphotos.log](https://github.com/user-attachments/files/16398920/ownphotos.log)

## Please provide additional information:
- 💻 Operating system: Windows 11 Pro Version 10.0.22631
- ⚙ Architecture (x86 or ARM): x86
- 🔢 Librephotos version: idk where to find version number but i got it from here https://hub.docker.com/r/reallibrephotos/singleton
- 📸 Librephotos installation method (Docker, Kubernetes, .deb, etc.): Docker
    * 🐋 If Docker or Kubernets, provide docker-compose image tag: idk if this is it ---> Container ID: 1c64f4ad5b60
- 📁 How is you picture library mounted (Local file system (Type), NFS, SMB, etc.): fuse.shfs
- ☁ If you are virtualizing librephotos, Virtualization platform (Proxmox, Xen, HyperV, etc.): UNRAID

**Comment by derneuere** [comment]
A tried to reproduce it, there are multiple potential causes:

1. #715 only visible images will get downloaded, there is no way yet to "select all" and the download yet.
2. If you configured the proxy yourself, this part is important and should be kept https://github.com/LibrePhotos/librephotos-docker/blob/e42d8e749a5040ceab70ed0b53106d586519a269/proxy/nginx.conf#L25C5-L29C6
3. If there is already a long running job running than the download job did not start yet
4. The zip file gets downloaded first and then it will show the download dialog after it has already downloaded the file.

The real issue is probably the singleton image. It's quite old and not update to date anymore. I would recommend switching to docker compose instead :)
