### ISSUE TITLE
Add Multithreading / Batchprocessing

### ISSUE THREAD

**Issue by sysoppl** [LibrePhotos/librephotos#17]
I'm using local folder now. Each photo is scanned for about 8-10 seconds, while cpu usage is at about 20% with peaks to 40% (on 4c/8t xeon). 
Also, ram usage seems to be very low. 
I'm on default docker configuration. Maybe it is docker fault?
![image](https://user-images.githubusercontent.com/30871217/101243665-13685900-3702-11eb-9031-9c311bade162.png)
![image](https://user-images.githubusercontent.com/30871217/101243729-79ed7700-3702-11eb-82e6-c89b05b20a32.png)

**Comment by derneuere** [comment]
That would be an enhancement. Currently, it doesn't support batch processing or multi threading. RAM usage seems okay. At the moment we only use performance machine learning models, that are quite efficient.

**Comment by robertcontois** [comment]
Many of the current issues seem to revolve around the scan_photos process. That function and all of it's calls are pretty monolithic. Every image gets fully processed before the next image in the queue gets processed. 

I could look at rewriting this a bit and breaking it up some, for example:

- save photos in the DB before doing all the intensive work  
- remove the rescan option from the list of function calls since it looks like that doesn't full rescan a photo
- run some of the more intensive jobs as a background process

There are probably other optimizations I could make but that's what popped out at me.

**Comment by derneuere** [comment]
I agree that we should split it up to show the images quicker and I like the idea of a background process for the ml classifiers!

We still need the rescan function. I know that I haven't implemented it fully, but it is essential, because users will change the data all the time. We should implement it completely including handling of moved images and a new job to clean the database of deleted images.

@sim4city wanted to implement that together with a migration to [ulid ](https://github.com/ulid/spec)as unique identifier and [imagehash ](https://github.com/JohannesBuchner/imagehash/) as new hash.

See: https://github.com/LibrePhotos/librephotos/wiki/Open-Discussion:-Hashing and https://github.com/LibrePhotos/librephotos/wiki/Open-Discussion:-Primary-key-and-migration-of-primary-key

**Comment by robertcontois** [comment]
I'm not saying rescan isn't needed, but just not include it in the scan photos function call. The current button on the frontend can scan for new photos, but have a separate button to rescan existing photos. A user might only change files in 1 folder, or might only want to rescan for 1 type of change (exif and not faces). So the ability to choose why you are rescanning would be important to performance.

**Comment by derneuere** [comment]
Rescanning items does not create a huge overhead. I think UX wise it is expected that when you scan a directory, to also rescan it. Examples for that would be plex or jellyfin

**Comment by robertcontois** [comment]
Scanning in plex scans a folder for new or removed media. Right now the rescan only updates exif data and generates thumbnails if they don't already exist. In Plex:

- if a new file is found it's added to the DB and the metadata is gathere
- if a file is found to have been removed it is removed from the DB
- If a file already exists in the database nothing is done

Rescanning/Downloading metadata for existing files in Plex is performed as a separate function. 

If I have a very large collection of photos I don't necessarily want to rescan all my existing photos for changes everytime I just want to scan for new photos. 

Many people are running LP on NAS hardware so any savings in resources can be a huge benefit.

**Comment by tomamplius** [comment]
if someone can test  #206?

**Comment by derneuere** [comment]
Thanks to @tomamplius this is now implemented 🥇
