### ISSUE TITLE
Getting error "This image failed to load"

### ISSUE THREAD

**Issue by scadaguru** [LibrePhotos/librephotos#180]
It is not showing any picture and when I double click on an "empty" image it says "This image failed to load"
I am running latest dev version in docker. I see many empty boxes under recently added section.
Any idea?

**Comment by jaypi95** [comment]
I have the same issue and it always logs this kind of error: 

`librephotos-proxy    | 2021/03/02 23:04:17 [error] 28#28: *502 open() "/protected_media/square_thumbnails/04be1eec96d3cbe196be9cffce21578e1.jpg" failed (2: No such file or directory), client: 172.27.0.1, server: , request: "GET /media/square_thumbnails/04be1eec96d3cbe196be9cffce21578e1.jpg HTTP/1.1", upstream: "http://172.27.0.5:8001/media/square_thumbnails/04be1eec96d3cbe196be9cffce21578e1.jpg", host: "photos.DOMAIN.ch", referrer: "https://photos.DOMAIN.ch/"`

**Comment by kkAtGithub** [comment]
I have the same problem.

**Comment by DigitalWarrior** [comment]
1. Was there any changes to the proxy or ip addresses?
2. Did you set this up in the .env and ensure the directory was created (it is not automatically created) and able to be accessed by docker?
Protected media directory. This is where we store some files like the thumbnails of your images. 
proMedia=./librephotos/media

**Comment by jaypi95** [comment]
No there were no changes between updates. It worked at first when I set it up.

The folder exists and it and its contents are also visible from within the backend container. 
Does the folder have to have special permissions?

I just tried it out and and I can find the thumbnail in the error message above:

```
root@6645e023ae56:/code# ls -lah /protected_media/square_thumbnails/04be1eec96d3cbe196be9cffce21578e1.jpg
-rw-r--r-- 1 root root 55K Mar  4 10:53 /protected_media/square_thumbnails/04be1eec96d3cbe196be9cffce21578e1.jpg
```

**Comment by derneuere** [comment]
Okay, I think this is a CORS issue, but I am not sure. Does it work when you don't host it over the internet but locally? I thought that I changed all requests to use the http://backend instead, but maybe I understand NGINX wrong:
https://github.com/LibrePhotos/librephotos-docker/blob/main/proxy/nginx.conf

You could also try setting "BACKEND_HOST" as a new variable in you .env file, because it should also allow you to set it to your domain name manually:
https://github.com/LibrePhotos/librephotos/blob/e91b4edd8b9fa4449337eaafcdc35ae79b2a3750/ownphotos/settings.py#L28

**Comment by jaypi95** [comment]
Not sure what you mean with locally or over the internet. It is running on a server but the server is in the same network as my client and they have the same lookup domain configured. If by locally you mean I have to run it on the same computer then I would have to try this because that server in particular is headless. Despite that I tried this variable first with my backend.mydomain but that didn't work at all and I tried it with the internal IP address of the container which gave the same result as just having backend.

Also: I'm able to resolve backend to the correct container from within docker so it seems to work.

Also also: I tried recreating the whole config folder since it worked in the beginning (I set it up at the end of february I think) but nothing changed.

**Comment by DigitalWarrior** [comment]
I just had a similar issue. 
After doing a docker-compose pull I would get 
![image](https://user-images.githubusercontent.com/802654/111014201-d8f50480-835f-11eb-90cc-e6dd6c32709a.png)

The scan was working but no thumbs are created and when you click on an image you get the "This image failed to load"

It worked after updating the docker-compose.yml. 
docker-compose down
wget https://raw.githubusercontent.com/LibrePhotos/librephotos-docker/main/docker-compose.yml
docker-compose up -d

Depending on when you last updated your .env it might also need to be updated to support the new variables.

**Comment by jaypi95** [comment]
So I had to update my docker-compose since debian ships an older version in its repositories and I recreated everything but it didn't change anything. 

What permissions do you have for your folders (media, cache, data etc)? I tried changing them around but this only made it worse.

My current permissions are:
```
drwxr-xr-x  6 root             root 4.0K Mar 12 14:26 .
drwxr-xr-x  4 root             root 4.0K Mar 14 01:26 ..
drwxr-xr-x  4 root             root 4.0K Mar 12 14:28 librephotos_cache
drwx------ 19 systemd-coredump root 4.0K Mar 14 01:29 librephotos_data
drwxr-xr-x  2 root             root 4.0K Mar 13 14:17 librephotos_logs
drwxr-xr-x  2 root             root 4.0K Mar 12 14:26 librephotos_media
```

**Comment by jaypi95** [comment]
Alright so I removed all the folders, config and containers. Used the docker-compose from above, recreated and re-filed-out the .env and now it seems to be working. It's scanning files and has already found about 2500 photos and so far everything works.
