### ISSUE TITLE
Rename Recognized Person

### ISSUE THREAD

**Issue by mirisbowring** [LibrePhotos/librephotos#269]
I just started to test if librephotos fulfills my needs.

**Describe the enhancement you'd like**
I made a spelling mistake for a recognized Person (presse m instead of n).
No I would like to rename the person with the correct spelling without recreating and reclassifiing again.

**Describe why this will benefit the LibrePhotos**
This will save much time to users that are doing mistakes like me.

**Comment by josarsepi** [comment]
@mirisbowring , for now, you can select the first image and then use CTRL+SHIFT and select the last image to grab all images between the first and last without having to click each photo separately.  Once you have the group selected you can create the new grouping like normal.  Otherwise, I agree that it would be a good enhancement to have the ability to rename the groups without have to completely group them.

**Comment by derneuere** [comment]
You can now rename a person.

**Comment by mirisbowring** [comment]
Thank you!
