### ISSUE TITLE
Face Labeling workflow: Cluster distinct "unknown" faces for easy labeling

### ISSUE THREAD

**Issue by ChrisFab16** [LibrePhotos/librephotos#284]
Provide an option to group similar faces in the unknown category.

This would enable faster labeling and training

**Comment by derneuere** [comment]
I added a new function to cluster unknown faces to groups: https://github.com/LibrePhotos/librephotos/blob/6abe88709bbefce7d4bbd02f306d68022c159689/api/face_classify.py#L46

I have to still implement #60 , so that we actually have unknown faces left to cluster and I have to add a new type of person, that was automatically determined with the algorithm. This change also has to be reflected in the frontend.

**Comment by jakekapellen** [comment]
I've created a fork of this and have a 90%-working implementation of this in the backend. See https://github.com/jakekapellen/librephotos for my current implementation.

As of today, it clusters all the unlabeled faces into groups and creates the "unknown" person type. When rerunning the clustering, it cleans up the unknown people "owned" by the user (using the "account" field) and regroups the photos.

It then furthers calculates the probability that a given "unknown" face belongs to the cluster of unknown faces by calculating the p-value based on its distance from the "center" of the cluster (the "average face" as determined by the 128d encoding). As expected, it seems to stratify the faces into about 80-90% confidence levels. I need to double-check my math here to make sure I'm doing it right...

Either way, @derneuere, I'll create a pull request once I have it working. Let me know if you want to collaborate on the design here.

**Comment by derneuere** [comment]
Awesome! The user Nikkelitous on discord, who works as a data scientist, explained to me why and when to use multiple clusters for one person:

Clusters should be generated using the same rule.  If you're going off a distance from a center face, that'd mean that any faces outside that range would be excluded from that cluster.  However, you could still have other faces that match that identity.  You'd then create a new cluster containing whichever those go to.
It's basically impossible to provide a specific number of bins (what it's called when you're using kmeans to cluster on its own)  There are some prediction algorithms, but they're finicky.
In your example, what I'd say is that you'd instead have one person that is mapped to multiple clusters behind the scenes.
If you add a new face that doesn't fit into an existing cluster, you'd add a new cluster to that face.
The feature extracts (encodings) can be cached and then compared.  You could potentially cache the min/max of the whole cluster (if you use dynamic clusters).
A quick primer on the dynamic cluster: Instead of using a single "key face" for each cluster, you take that face and compute the mean and std of the whole cluster.  Then you use that to determine new entrants to the cluster.
Don't try computing every face against every other face, that's HUGELY wasteful.
Instead, you treat each cluster as it's own thing and compare against those.
I suggest the library https://pypi.org/project/fastcluster/ which can do the comparisons very quickly and efficiently.
It's a pretty easy replacement for scipy's linkage clustering.
It can even do a special mode where it saves memory but operates slower in case you're doing a LOT of comparisons at once.

Hope it helps!

**Comment by jakekapellen** [comment]
That's great, and almost identical to how I'm doing this (I couldn't find good resources on computing the probability since DBSCAN doesn't work like that).

I love the suggestion on how to add new entrants to the cluster. I can save off cluster stat details for each cluster (in Person) then find the cluster with the highest p value when adding a new face. From there, I'd update the stats and average face given the new face.

I'll let you know once I'm further along. I have some non trivial work to do in other parts where we identity the unknown person as being singular with a specific name; I'll need to relax that assumption now.

**Comment by jakekapellen** [comment]
I've committed a lot of changes to my own fork at this point; it isn't ready for release yet, but if you'd like to take a look, you're welcome to do so. Sorry in advance for the novel here, but this is pretty complicated and should help you to review the pull request when it eventually comes in.

In general, here's the overview of the new clustering algorithm:
- Clicking Train Faces actually kicks off a new job I've created, called "Finding Similar Faces." It uses DBSCAN to cluster all faces, both known and unknown, into clusters.
- From there, it loops over all the clusters and confirms that the faces in each of them corresponds to AT MOST 1 "labeled" person. If the cluster has multiple people (suppose you have two similar-looking people, like children of the same parents), it will split the cluster based on the known faces present and group the remaining unknown faces based on their Euclidean distance from the sub-cluster means (the centroids, technically). This process ensures that each now-split cluster corresponds to precisely 1 person, either known or unknown (found by DBSCAN but not labeled).
- The above process actually permits multiple clusters to correspond to the same person. This is important because the current algorithm doesn't handle the different "faces" that a person has over time. For example, my kids at birth are very different than they are now (my eldest is 9), so the old algorithm would fail badly by grouping all infants together, for example, even if that is wrong. The old algorithm would require you to label at least one "Kid 1 infant" picture and a "Kid 1 elementary age" picture as "Kid 1" before it could distinguish. Now, it does this on its own by creating a separate Unknown cluster for the unique faces.
- At this point, everyone is clustered, but the probabilities/confidence %'s are wrong. I now kick off a modified form of the old "Train Faces" job. It is similar to before, but I added a step where I add the means of each unknown person cluster (technically the centroids) to the "known faces" before training the model. This is akin to assuming that the unknown cluster represents a real person, then seeing how well the unknown faces fit that assumption. I then ignore the predicted person for each face (since DBSCAN handled that before), and instead take the probability corresponding to the face that DBSCAN returned instead. This allows me to get the probability that any given unknown face corresponds to a known face (or an unknown face cluster) that we care about, instead of just taking the maximum probability (since we've split the job between DBSCAN and the MLPClassifier now instead).

Here's what I still am likely to do:
- Modify the definition of "unknown person" throughout the code so that it isn't just looking for a name of "unknown." The old behavior is not I18N-safe, and the clustering behavior relies on the face being associated with an unknown person in another way.
- Update new faces to automatically cluster them. I have a simple algorithm that just associates it with the nearest cluster (based on Euclidean distance from the mean); this is different than using DBSCAN, but it is probably good enough for now. I need to update it to set the probability to be correct, but it is 95% there. I worry about performance a bit here if I am constantly re-training the same MLPClassifier to get the probability. The API allows multiple new faces to get passed in, so we could do the update in bulk to cut down on the prediction time by just doing it once.

Here's what I am considering doing (let me know if you think any of these should be prioritized):
- Move from DBSCAN to SSDBSCAN (semi-supervised DBSCAN). There is no standard library for this, so I'd have to write it myself (which may take a week or more). This would allow me to replace much of the algorithm above with a proper clustering technique that takes the labels into account up front. The downside here is that SSDBSCAN would likely create combined clusters for a given person (instead of just clustering faces and seeing what happens), reducing effectiveness when classifying kids who change faces over time.
- Moving the "Other Unknown" and "Unknown XYZ" strings to the client (and send them down as parameters in the appropriate views) so we can use Weblate to translate them. If you know of a way to utilize Weblate on the backend, let me know.
- Automatically kick off reclustering when scanning a directory.
- Finding a way to associate clusters with "owners." As it is right now, we clear out all clusters and unknown people whenever we redo clustering, meaning that having multiple users do this could run into some weird behavior where other users interfere with each other.

Here's what will almost certainly be separate:
- I made some UI tweaks to clean up some strings that were pretty technical-sounding.
- I plan to allow multi-select and "Select Group" in the faces pages to allow for easily labeling an entire group of clustered faces.

**Comment by derneuere** [comment]
This is now implemented :partying_face: Still a few couple of bugs, but I tracked them in other issues.
