### ISSUE TITLE
Duplicated faces on rescan faces

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#330]
Face recognition is not deterministic and will sometimes create slightly different location points for a face. If you rescan faces, then this will lead to duplicates of the same face.

To reduce the number of duplications, this function should check all faces for an image. If none match the new faces within a certain margin (+-5%), then add the face. Otherwise, skip.

Maybe this is possible to do within the getOrCreate call, but I haven't checked up on the documentation yet.

https://github.com/LibrePhotos/librephotos/blob/8d834d9721b56656441be74b4c5bacb7200698f2/api/models/photo.py#L320-L364

**Comment by derneuere** [comment]
@rootkie Do you got some time to implement that? 😄

**Comment by rootkie** [comment]
> 
> 
> @rootkie Do you got some time to implement that? 😄

Oh I did not know that face recognition is not deterministic... Can I get some sample photos because I can't reproduce this bug in my library. I get back the exact number of faces each rescan.

I think can get all faces associated with current photo and check if current face is within margin of any faces. However this will make photos with more faces take longer to process. 

As for doing it within the get_or_create call, I don't see any mention of fuzzy matching in the documentation for integer values. Might try using Q object like
```python
Q(location_top__gte =  face_location[0]*0.95), 
Q(location_top__lte = face_location[0]*1.05)
```
But I have only seen it used for filter, not sure if it works for get_or_create
