### ISSUE TITLE
Batch process "generating clip embeddings"

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#358]
After a user reported that the scan took a long time for him, I investigated and logged each step. The result is that for a normal JPEG generating clip embeddings takes up 70% of the scan time or 7.3 seconds on my machine. 

I think this could be improved by batch processing the images at the end at saving them then. 

This would allow us to keep the speed high, while allowing for advanced features like semantic image search and finding similar images.

**Comment by derneuere** [comment]
@akshay9 Do you want to try it out and see if it is any faster? 😄

**Comment by akshay9** [comment]
I previously tried this, and it does makes embedding calculation about 10 times faster. 

I have implemented it in scenario when "A user disables Semantic Search, Adds some new photos, and then re-enables semantic search". In this case the clip embeddings are calculated using batches for the new photos.
Code : https://github.com/LibrePhotos/librephotos/blob/dev/api/batch_jobs.py

But to implement it in the new photo scan step (in directory_wathcer.py), will require a bit of refactoring of the entire function.
Currently we are using the starmap function which assigns just a single image to the handle_new_image function, so instead of 1 we need to pass batches of 5-10 images. 

Pytorch works best when multiple cores are assigned to it with a batch of images instead of running the model on each core with a single image. Number of cores used by pytorch can be easily configured by `torch.set_num_threads()`
