### ISSUE TITLE
Improve Face Recognition Photo Popup

### ISSUE THREAD

**Issue by troycarpenter** [LibrePhotos/librephotos#394]
When training faces, there is a small icon to bring up the photo from where the face was captured.  However, this helper photo is usually not very big, so a method to have other hints would be nice.  Within a family, faces are usually very similar, so may times (especially with baby faces) the only way to tell who belongs to the face is to have access to the EXIF data with a date the photo was taken.

I would like to be able to click on the photo and be taken to the normal size photo with access to the EXIF data.  With access to other data, especially the date of the photo, I could more accurately identify the face.

**Comment by trowj** [comment]
I think something also worth considering is adding a box or circle on the face found - like Google does on the 'Same Person?' popup - to make it easier to tell which person it's talking about. Some small found faces or ones with very similar people can be hard to tell
![image](https://user-images.githubusercontent.com/7526864/141564106-92e00000-d89b-4013-861d-e946cb5bce85.png)

**Comment by 5m4u66y** [comment]
My proposed solution (#663) to this issue is to display the date in the tooltip. It is a fast and easy way to have access to the date the photo was taken, which is indeed an essential information to identify babies.
In order to get other EXIF data and the full size photo, issue #457 need to be implemented.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/115424459/195463771-c29b0999-00dd-4081-9673-50973494b878.png">
