### ISSUE TITLE
Very big people album with 10k+ pictures does not load

### ISSUE THREAD

**Issue by sefininio** [LibrePhotos/librephotos#408]
**Describe the enhancement you'd like**
I have a few people faces tagged.
When I navigate in the UI to albums/people and select a person with, say, up to ~3000 pictures, the album loads fine and I can see all pictures.

But, when I navigate to a person album with more pictures (some have as much as 6k to 11k pictures) then the album never loads, I see constant spinner for a very long time - even 10 minutes before I give up.

I cannot see any errors in the frontend/proxy/backend logs.

I think that server side pagination with infinite scroll page load mechanism will solve the issue. Page can be relatively big, easily in the hundreds of pictures per page. 

Things to consider: this will probably also affect filters when the server does the pagination. 

**Describe why this will benefit the LibrePhotos**
This is a major usability issue, since it renders people albums with a lot of pictures practically useless. 

**Additional context**

**Comment by sefininio** [comment]
Any news on this issue?
This problem seems to be already solved for `Photos with timestamp` album - it loads placeholders and then loads the visible pictures.. Can we apply the same mechanism for people albums as well?

**Comment by sefininio** [comment]
@derneuere 
If you point me in the right direction in the `librephotos-frontend` code, I might be able to open a PR for this.

**Comment by derneuere** [comment]
It has a lot of moving parts. I will stream on monday and will work on this problem. Not sure if I will get it done in one session or if that needs more time.

These are the subproblems:
- Load non timestamp photos together with timestamped images
- Change the order, that non timestamp images are at the end
- We require subpagination of an album date, because non timestamp images could be large. This will require some work on the frontend, but not a lot. 
- We will probably have to change react-pig, because we only get currently the visible group, but not the visible items of the group.
- Add another filter for the query for persons
- Figure out how we can efficiently merge the photos of the person and timestamp photos
- Change the functions and the redux store in the frontend for the person view

**Comment by derneuere** [comment]
Finished up the first four points. I need to debug a bit with django-debug-toolbar why the query is slow, but I think I will only need one more session to implement it.

https://www.youtube.com/watch?v=UxI2SENyaLk

**Comment by derneuere** [comment]
Alright, subpagination is now fast and was added.

**Comment by sefininio** [comment]
Awesome! Thanks for the hard work

**Comment by derneuere** [comment]
Thanks, but I still have to do the last three points 😄 I hope that this will now be easier to implement.

**Comment by derneuere** [comment]
Finished it up. Now person albums load fast. Available on the dev branch or in a week on latest

**Comment by sefininio** [comment]
Incredible!
