### ISSUE TITLE
Enhancement:  Face editing while photo browsing

### ISSUE THREAD

**Issue by linuxturtle** [LibrePhotos/librephotos#480]
As a user, I would like to be able to label faces from within the "lightbox" photo browsing component.  The sidebar already shows labels corresponding to faces in the photo, but clicking on those labels drops me out of the lightbox, losing all context, and searches for the name, with no way to go back to the photo I was browsing.  I would suggest displaying the faces alongside the labels, and allowing to click on them to edit their labels in the same way as the face dashboard.  I've attached a mockup to illustrate what, to my inexpert eye, looks like the easiest way to implement the desired functionality.

![Lightbox+Sidebar+faces-mockup](https://user-images.githubusercontent.com/135536/161346120-4be14dae-89ba-4054-87a1-9fe3b86fd90b.png)

Rationale: The existing face dashboard is an awesome way to label faces, but it's unwieldy when many thousands of faces are in the archive needing to be labeled, and it's also very difficult to find all the faces which are desired to have labels.  It would be much easier to start from a photo (a family portrait, for example), and label everyone in the photo, or while browsing photos, when I see a label that is wrong, to simply fix it in place.  Then once a good number of people are defined, the existing face dashboard is ideal for confirming matches.

I would love to contribute this enhancement, but I find myself lacking in understanding of how.  I found the place in components/lightbox/Sidebar.js where the existing "search" functionality is implemented, and removed it, and I found the "addFaces()" function in layouts/dataviz/FaceDashboard.js, but I don't understand enough about the structure of the frontend, or React, to go much further without some guidance as to how this might be done.  I've written a lot of low-level C code and shell code, but have only dabbled in web development.

**Comment by derneuere** [comment]
A couple of notes on how I would display the faces:

- Replace the [person icon](https://github.com/LibrePhotos/librephotos-frontend/blob/baee77c5f8d94c40f019308c47dc14b7a11c4207/src/components/lightbox/Sidebar.js#L127-L140) with a small rounded version of the face like [Face Cluster View](https://github.com/LibrePhotos/librephotos-frontend/blob/baee77c5f8d94c40f019308c47dc14b7a11c4207/src/components/charts/FaceClusterGraph.tsx#L79-L89). I think I would need to change up the [PhotoSchema](https://github.com/LibrePhotos/librephotos-frontend/blob/baee77c5f8d94c40f019308c47dc14b7a11c4207/src/actions/photosActions.types.ts#L44-L66) as the people are currently only names.
- When hovering over a name of a person, the face in the picture gets outlined / highlighted. I think I would need to do a couple of changes in the backend. If you want to implement this too, let me know 😄 

The advantage is that it does not take up more space while showing more information. 

How editing should work in the first version:
- Add an edit button similar to the edit button for time taken
- Clicking on a name opens up a [ModalPersonEdit](https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/components/modals/ModalPersonEdit.js)

Ideally, it would be something like:
- After clicking on the edit button, it becomes a [dropdown](https://react.semantic-ui.com/modules/dropdown/), where you can select a person and optionally add a new person.

On how to approach this:

- Create a new component for the people section like [TimestampItem](https://github.com/LibrePhotos/librephotos-frontend/blob/dev/src/components/lightbox/TimestampItem.tsx) with the name PeopleItem
- There you would handle the state for opening up a new ModalPersonEdit and EditMode
- This component would render the people section and the editing context
- Replace the current people section with the new component

Each react component has a state and props. addFaces changes the state modalPersonEditOpen to true. This will make the ModalPersonEdit visible, because we give this state as a prop to the component. ModalPersonEdit also knows about the selected faces, because we give that state of selectedFaces as prop too. You can find more information about props and states [here](https://reactjs.org/docs/components-and-props.html)

**Comment by linuxturtle** [comment]
Wow, thanks for the quick response!  Looks like I've got some homework to do! :laughing:  I love the idea of highlighting the faces in the photo when hovering over the name.  I think that would remove the need to modify the person icon at all (I thought displaying the faces as part of the icon would make it consistent with the face dashboard, but the hover-highlight idea is a much better way IMO, and that could leave the person icon just a named button).  I have no clue how that might be done though.  I'll give your suggestion for creating a new component a try, and see if I can figure out where to get and set the state properly to open up a ModalPersonEdit, and go from there.

**Comment by derneuere** [comment]
Alright, I added this while refactoring everything to the new UI :smile:

**Comment by derneuere** [comment]
Alright, I added this while refactoring everything to the new UI :smile:
