### ISSUE TITLE
Login does not work correctly with case sensitive usernames

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#487]
We currently save the usernames always in lowercase, but the app does not convert the input of the username to lowercase. Therefore a user could get confused as he can't login.

**Comment by polaroidkidd** [comment]
Should the app also force lower case usernames or should the backend allow a lower/uppercase username?

Personally, I'd find it confusing to have two separate logins because one is uppercase. Additionally, I think that phones capitalize the first letter in input fields as well. Converting it to lower case in the app makes the most sense to me.

**Comment by savvasdalkitsis** [comment]
Is the lowercase enforcement going to be a feature going forward? I am thinking whether to enforce lowercase on UhuruPhotos during login if this is the intended behaviour

**Comment by derneuere** [comment]
I think we will keep it that way for now, so it would be make sense to enforce it in UhuruPhotos.
