### ISSUE TITLE
Lack documentation

### ISSUE THREAD

**Issue by PiotrEsse** [LibrePhotos/librephotos#654]
**Describe the enhancement you'd like**
Improve documentation

**Describe why this will benefit the LibrePhotos**
Give more users and help with media traction

If find lack od documentation quite hard for new users to step in. I can help with documentation but need an condensed input from developer/s.

If I receive a document in any form, I'll prepare documentation by add more text, expand descriptions, structuralize it, divide it into proper structure.

**Comment by derneuere** [comment]
It's not clear on what to improve exactly. The docs are here https://docs.librephotos.com/

**Comment by PiotrEsse** [comment]
Hi, I was refering to many options being present without any clarification.  
IE:At settings page - what those options mean?

![image](https://user-images.githubusercontent.com/42764623/193987051-abec756c-bed9-4314-98f9-b4359319562a.png)

**Comment by derneuere** [comment]
Thanks for clarifying! 

Scene Confidence: It determines how high the confidence should be when finding new tags. They are shown in the lightbox here or as a thing album: 
![image](https://user-images.githubusercontent.com/6658807/194027689-2c56f698-33e4-42ff-a39c-7a6d7094dee1.png)

Semantic Search Max Results: Instead of only looking for filename, tags or EXIF data, you can enable semantic search. You can the use any phrase like "a bunch of deer" and should get the relevant images back. It's right now not activated by default, because it only works in English, first search takes a while, and it's not yet clear how many resources it needs.
Example: 
![image](https://user-images.githubusercontent.com/6658807/194028393-1d2a47e7-866e-4254-aebd-9dade6e50379.png)

Synchronize metadata to disk: We have a two EXIF fields that already can be saved back, if you change it. This is the rating tag and the EXIF:OriginalTimestamp. You can choose if you want to save this data within an XMP file or the original file.

Minimum image rating to interpret as favorite: Default is 3. There is no such thing as a favorite within the exif data, but a rating tag exists. This sets how the metadata should be interpreted. Higher means it's a favorite, lower means it's not. If you activated "Synchronize metadata to disk", it will also change how a favorite is saved.

You can also just try things in the demo instance, if you want to figure out how something works. It gets reset every couple hours :)

Looking forward to the PR in the docs repository :)

**Comment by PiotrEsse** [comment]
Dear Niaz, 
thank You for clarification. 
I already install LibrePhotos on my server. Ive checked many, many photo repositories, use extensively few (ie: PhotoPrism) but in my opinion LibrePhotos it the most promising one. Really. It get traction but there are few steps which help users step in - and main is user documentation. 
Also, I can help with Polish translation - Ive already open another ticket asking for Weblate project reopen. 

You are doing a fantastic job, really. Thank You. 
Piotr
