### ISSUE TITLE
Document secret.key

### ISSUE THREAD

**Issue by derneuere** [LibrePhotos/librephotos#818]

**Comment by yodatak** [comment]
Hello i just delete it and cannot recover the problem because i was thinking it was in log folder so i can delete easy ( i think we shoudl move to another folder)

I'm now stuck
how can i fix it ?

[backend]  | During handling of the above exception, another exception occurred:
[backend]  | 
[backend]  | Traceback (most recent call last):
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/rq/worker.py", line 1061, in perform_job
[backend]  |     rv = job.perform()
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/rq/job.py", line 821, in perform
[backend]  |     self._result = self._execute()
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/rq/job.py", line 844, in _execute
[backend]  |     result = self.func(*self.args, **self.kwargs)
[backend]  |   File "/code/api/apps.py", line 18, in build_index
[backend]  |     for user in User.objects.all():
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 287, in __iter__
[backend]  |     self._fetch_all()
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1308, in _fetch_all
[backend]  |     self._result_cache = list(self._iterable_class(self))
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 70, in __iter__
[backend]  |     for row in compiler.results_iter(results):
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1100, in apply_converters
[backend]  |     value = converter(value, expression, connection)
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/fields.py", line 173, in from_db_value
[backend]  |     return self._load(force_bytes(value))
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/fields.py", line 115, in _load
[backend]  |     return pickle.loads(self._fernet.decrypt(value, self.ttl))
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/utils/crypto.py", line 143, in decrypt
[backend]  |     data = self._signer.unsign(data, ttl)
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/core/signing.py", line 239, in unsign
[backend]  |     raise BadSignature(
[backend]  | django.core.signing.BadSignature: Signature "b'4f6Bb0SauWWJ5sbasSq/UiD4m1gHK1i81mwtsLh8VWg=\n'" does not match
[backend]  | Traceback (most recent call last):
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/core/signing.py", line 237, in unsign
[backend]  |     self.signature(signed_value[:-d_size]).verify(sig)
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/primitives/hmac.py", line 70, in verify
[backend]  |     ctx.verify(signature)
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/cryptography/hazmat/backends/openssl/hmac.py", line 84, in verify
[backend]  |     raise InvalidSignature("Signature did not match digest.")
[backend]  | cryptography.exceptions.InvalidSignature: Signature did not match digest.
[backend]  | 
[backend]  | During handling of the above exception, another exception occurred:
[backend]  | 
[backend]  | Traceback (most recent call last):
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/rq/worker.py", line 1061, in perform_job
[backend]  |     rv = job.perform()
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/rq/job.py", line 821, in perform
[backend]  |     self._result = self._execute()
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/rq/job.py", line 844, in _execute
[backend]  |     result = self.func(*self.args, **self.kwargs)
[backend]  |   File "/code/api/apps.py", line 18, in build_index
[backend]  |     for user in User.objects.all():
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 287, in __iter__
[backend]  |     self._fetch_all()
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1308, in _fetch_all
[backend]  |     self._result_cache = list(self._iterable_class(self))
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 70, in __iter__
[backend]  |     for row in compiler.results_iter(results):
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1100, in apply_converters
[backend]  |     value = converter(value, expression, connection)
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/fields.py", line 173, in from_db_value
[backend]  |     return self._load(force_bytes(value))
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/fields.py", line 115, in _load
[backend]  |     return pickle.loads(self._fernet.decrypt(value, self.ttl))
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/utils/crypto.py", line 143, in decrypt
[backend]  |     data = self._signer.unsign(data, ttl)
[backend]  |   File "/usr/local/lib/python3.10/dist-packages/django_cryptography/core/signing.py", line 239, in unsign
[backend]  |     raise BadSignature(
[backend]  | django.core.signing.BadSignature: Signature "b'4f6Bb0SauWWJ5sbasSq/UiD4m1gHK1i81mwtsLh8VWg=\n'" does not match
