### ISSUE TITLE
Mobile optimized UI

### ISSUE THREAD

**Issue by jorge-aparicio** [LibrePhotos/librephotos#99]
I noticed that librephotos currently does not behave the best on mobile devices. There are some tweaks that could make this experience better such as moving the side bar to the bottom of the screen on mobile devices and ensuring the other elements are spaced well on mobile devices.  However, these are just my ideas. Overall, librephotos would benefit greatly from having a mobile UI which would be in line with its goals of being a replacement for Google Photos. This would be an amazing step towards achieving that goal!

![photo_2021-01-03_17-55-00](https://user-images.githubusercontent.com/43185027/103494704-d076cf80-4dec-11eb-86e9-0e2db73520ec.jpg)

**Comment by sysoppl** [comment]
It looks good on my Phone 

![Screenshot_20210104-100654~2](https://user-images.githubusercontent.com/30871217/103519127-47f04180-4e75-11eb-8881-ba0c56fe31be.png)
![Screenshot_20210104-100716~3](https://user-images.githubusercontent.com/30871217/103519130-4888d800-4e75-11eb-95c6-b9824e3e55a3.png)

Probably due to Phone screen resolution

**Comment by jorge-aparicio** [comment]
That could be it my phone is 1440p at 19.5:9 aspect ratio so definitely not standard
